# Generated by Django 3.0.7 on 2020-06-06 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.TimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField(max_length=3000)),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_description', models.CharField(max_length=300)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
