# Generated by Django 3.0.7 on 2020-06-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200606_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
