# Generated by Django 3.0.7 on 2020-06-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200606_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
